import { PageExplanationConfig } from "./types";

export const INHERITANCE_PARADOX_EXPLANATION: PageExplanationConfig = {
  pageKey: "inheritance-paradox",
  pageTitle: "Inheritance Paradox",
  scientificQuestion: "Why can an offspring phenotype fall outside the range of both parents?",
  totalDuration: 22,
  finalThesis: "Same parents. New combinations. New possibilities.",
  technicalDetail: {
    title: "Transgressive Phenotypic Segregation & Cis-Epistasis",
    biologicalContext: "Classical additive models predict offspring traits will blend between parental bounds [P_min, P_max]. When recombination reshuffles linked repelling alleles into cis configurations, positive complementary alleles synergize via non-linear metabolic networks.",
    computationalRole: "Simulates parental phenotype bounds, computes mosaic recombination, and evaluates non-additive epistasis terms γ_uv x_u x_v to quantify the transgressive margin.",
    formula: "y_{\\text{off}} > \\max(P_A, P_B) \\iff \\Delta z = y_{\\text{off}} - P_{\\max} > 0",
    keyTakeaway: "Offspring transgression emerges deterministically from recombination-assembled non-linear epistasis.",
  },
  scenes: [
    {
      id: "parental-range",
      index: 0,
      title: "Parental Range",
      duration: 5,
      simpleText: "Offspring do not always fall between their parents.",
      technicalText: "The parental phenotype envelope defines the range between the two parental values under the configured model.",
      annotationBadge: "PARENTAL ENVELOPE [P_min, P_max]",
      annotationSub: "Parent A (12.4) & Parent B (14.1) Baseline Limits",
    },
    {
      id: "genomic-config",
      index: 1,
      title: "New Genomic Configuration",
      duration: 5.5,
      simpleText: "Recombination can create combinations the parents do not carry in the same form.",
      technicalText: "Meiotic recombination assembles new haplotype configurations from existing parental alleles.",
      annotationBadge: "RECOMBINANT HAPLOTYPE ASSEMBLY",
      annotationSub: "Coupling Repelling Parental Alleles into Cis Orientation",
    },
    {
      id: "non-additive",
      index: 2,
      title: "Non-Additive Interaction",
      duration: 5.5,
      simpleText: "Some genetic effects become stronger when they act together.",
      technicalText: "Pairwise epistasis introduces non-additive contributions beyond simple locus-wise summation.",
      annotationBadge: "PAIRWISE EPISTASIS (A ↔ B)",
      annotationSub: "Non-Linear Coupling: γ_uv x_u x_v = +5.4 units",
    },
    {
      id: "transgressive-phenotype",
      index: 3,
      title: "Transgressive Phenotype",
      duration: 6,
      simpleText: "The offspring phenotype can move beyond both parents.",
      technicalText: "This is a transgressive phenotype under the configured genotype–phenotype model.",
      annotationBadge: "TRANSGRESSIVE SEGREGATION",
      annotationSub: "Offspring (18.7) Exceeds Parental Range [12.4, 14.1]",
    },
  ],
};

export const MEIOSIS_LAB_EXPLANATION: PageExplanationConfig = {
  pageKey: "meiosis-lab",
  pageTitle: "Meiosis Lab",
  scientificQuestion: "How does meiosis create genetically unique gametes?",
  totalDuration: 28,
  finalThesis: "Meiosis reshuffles inheritance. Crossovers and independent segregation generate alternative gamete configurations from the same parental homologs.",
  technicalDetail: {
    title: "Meiotic Cytogenetics & Gamete Provenance",
    biologicalContext: "During prophase I, homologous non-sister chromatids undergo synaptonemal complex zippering and reciprocal double Holliday junction resolution, producing recombinant mosaic chromatids before reductive division.",
    computationalRole: "Stochastically samples crossover break locations from species-specific recombination rate maps λ(x), tracks segmental provenance, and generates 4 haploid gamete matrices.",
    formula: "N_{\\text{crossovers}} \\sim \\text{Poisson}(\\lambda L), \\quad x_c \\sim \\text{Uniform}(0, L)",
    keyTakeaway: "Homolog synapsis and reciprocal crossover generate novel mosaic gametes without de novo mutations.",
  },
  scenes: [
    {
      id: "homolog-pairing",
      index: 0,
      title: "Homolog Pairing",
      duration: 5.5,
      simpleText: "Matching chromosome pairs align.",
      technicalText: "Homologous chromosomes undergo synapsis during prophase I.",
      annotationBadge: "SYNAPTONEMAL SYNAPSIS",
      annotationSub: "Maternal & Paternal Bivalent Recognition",
    },
    {
      id: "crossover-chiasma",
      index: 1,
      title: "Chiasma / Crossover",
      duration: 5.5,
      simpleText: "Chromosomes exchange matching segments.",
      technicalText: "Crossovers between homologous non-sister chromatids generate recombinant chromatids.",
      annotationBadge: "CHIASMA RESOLUTION",
      annotationSub: "Spo11-Induced Double-Strand Break Reciprocal Swap",
    },
    {
      id: "recombinant-chromatids",
      index: 2,
      title: "Recombinant Chromatids",
      duration: 5.5,
      simpleText: "New chromosome mosaics are created.",
      technicalText: "Recombinant chromatids contain segment-level ancestry from both homologous chromosomes.",
      annotationBadge: "FOUR CHROMATIDS (2 PARENTAL, 2 RECOMBINANT)",
      annotationSub: "Segment-Level Maternal/Paternal Linkage Tracing",
    },
    {
      id: "segregation",
      index: 3,
      title: "Segregation",
      duration: 5.5,
      simpleText: "The chromosome copies separate.",
      technicalText: "Meiosis I separates homologous chromosomes, followed by sister chromatid segregation during meiosis II.",
      annotationBadge: "REDUCTIVE DIVISION (MEIOSIS I & II)",
      annotationSub: "2n Diploid → 1n Haploid Reduction",
    },
    {
      id: "four-gametes",
      index: 4,
      title: "Four Gametes",
      duration: 6,
      simpleText: "Four genetically distinct gametes emerge.",
      technicalText: "Each haploid gamete carries one transmitted chromatid configuration.",
      annotationBadge: "FOUR UNIQUE HAPLOID GAMETES",
      annotationSub: "Substrate for Fertilization & Offspring Assembly",
    },
  ],
};

export const PHENOTYPE_ENGINE_EXPLANATION: PageExplanationConfig = {
  pageKey: "phenotype-engine",
  pageTitle: "Phenotype Engine",
  scientificQuestion: "How does the offspring genotype become a phenotype in our model?",
  totalDuration: 25,
  finalThesis: "From inherited genotype to model-relative phenotype.",
  technicalDetail: {
    title: "Non-Linear Polygenic Phenotype Decomposition",
    biologicalContext: "Metabolic networks process genomic signals through enzyme flux kinetics. Simple additive summation fails to capture biological non-linearities like dominance and epistasis.",
    computationalRole: "Maps discrete mosaic haplotype dosages into quantitative trait indices through additive weights, dominance deviations, and higher-order pairwise epistatic tensors.",
    formula: "y(x) = \\sum_{i} \\alpha_i x_i + \\sum_{j} \\beta_j d_j + \\sum_{u < v} \\gamma_{uv} x_u x_v + \\epsilon",
    keyTakeaway: "Computational decomposition separates linear additive background from supralinear epistatic drivers.",
  },
  scenes: [
    {
      id: "genotype-input",
      index: 0,
      title: "Genotype Input",
      duration: 5,
      simpleText: "The model begins with the inherited offspring genotype.",
      technicalText: "Genotype state is represented through modeled locus states and inherited haplotypes.",
      annotationBadge: "GENOTYPE MATRIX G_off",
      annotationSub: "Phase-Resolved Allele Dosages: x_i ∈ {0, 1, 2}",
    },
    {
      id: "additive-effects",
      index: 1,
      title: "Additive Effects",
      duration: 5,
      simpleText: "Some genetic effects add together.",
      technicalText: "Additive contributions are represented by main-effect terms: Σ αᵢxᵢ",
      annotationBadge: "ADDITIVE GENETIC VALUE",
      annotationSub: "Linear Dosage Summation: Σ αᵢxᵢ",
    },
    {
      id: "dominance-terms",
      index: 2,
      title: "Dominance",
      duration: 5,
      simpleText: "Allele combinations can alter their contribution.",
      technicalText: "Dominance terms model genotype-state deviations from additive expectation.",
      annotationBadge: "DOMINANCE DEVIATIONS",
      annotationSub: "Heterozygous Non-Additivity: Σ βⱼdⱼ",
    },
    {
      id: "epistatic-network",
      index: 3,
      title: "Epistasis",
      duration: 5,
      simpleText: "Some loci interact non-linearly.",
      technicalText: "Pairwise epistatic terms capture interaction effects between modeled loci.",
      annotationBadge: "PAIRWISE EPISTASIS TENSOR",
      annotationSub: "Non-Linear Network Coupling: Σ γᵤᵥxᵤxᵥ",
    },
    {
      id: "phenotype-output",
      index: 4,
      title: "Phenotype Output",
      duration: 5,
      simpleText: "These contributions combine into the modeled phenotype.",
      technicalText: "The configured phenotype model integrates additive, dominance, and epistatic components.",
      annotationBadge: "FINAL MODELED PHENOTYPE",
      annotationSub: "Parent A (-0.92), Parent B (+0.48), Offspring (+1.48)",
    },
  ],
};

export const NOVELTY_TRACE_EXPLANATION: PageExplanationConfig = {
  pageKey: "novelty-trace",
  pageTitle: "Novelty Trace",
  scientificQuestion: "Which inherited genomic configuration best explains the unusual phenotype?",
  totalDuration: 26,
  finalThesis: "From unexpected phenotype to interpretable genomic evidence.",
  technicalDetail: {
    title: "Backward Computational Causal Attribution",
    biologicalContext: "Polygenic phenotypes involve thousands of loci. Identifying which specific inherited configurations drive an extreme trait requires decomposing the novelty delta without exhaustive wet-lab screening.",
    computationalRole: "Operates backward from the transgressive phenotype, generating candidate variants and epistatic pairs, evaluating counterfactual deltas, and ranking candidates via Shapley-style attribution.",
    formula: "\\phi_k = \\sum_{S \\subseteq N \\setminus \\{k\\}} \\frac{|S|!(|N|-|S|-1)!}{|N|!} [v(S \\cup \\{k\\}) - v(S)]",
    keyTakeaway: "Computational attribution isolates top candidate drivers while strictly preserving forward biological provenance.",
  },
  scenes: [
    {
      id: "start-from-phenotype",
      index: 0,
      title: "Start from Phenotype",
      duration: 5,
      simpleText: "We start from the unexpected outcome.",
      technicalText: "The trace begins from a transgressive phenotype detected relative to the parental envelope.",
      annotationBadge: "OBSERVED PHENOTYPIC NOVELTY",
      annotationSub: "Offspring Trait y = 18.7 (Beyond Envelope [12.4, 14.1])",
    },
    {
      id: "candidate-generation",
      index: 1,
      title: "Candidate Generation",
      duration: 5,
      simpleText: "We search for genomic configurations that could explain it.",
      technicalText: "The blind attribution engine generates candidate variants, inherited segments and pairwise interaction configurations.",
      annotationBadge: "CANDIDATE SEARCH SPACE",
      annotationSub: "Variants, Crossover Segments, & Epistatic Pairs",
    },
    {
      id: "counterfactual-evidence",
      index: 2,
      title: "Counterfactual Evidence",
      duration: 5.5,
      simpleText: "We test how much each candidate changes the modeled phenotype.",
      technicalText: "Candidates are evaluated using model-relative counterfactual phenotype deltas.",
      annotationBadge: "COUNTERFACTUAL PERTURBATION DELTAS",
      annotationSub: "\\Delta z_k = y(\\text{baseline}) - y(\\text{ablated } k)",
    },
    {
      id: "provenance-trace",
      index: 3,
      title: "Provenance Trace",
      duration: 5,
      simpleText: "We trace each candidate back to its parental origin.",
      technicalText: "Provenance links candidate configurations to transmitted homologs and inferred recombination intervals.",
      annotationBadge: "PROVENANCE HIERARCHY",
      annotationSub: "Parent → Homolog → Crossover → Segment → Candidate",
    },
    {
      id: "ranked-explanation",
      index: 4,
      title: "Ranked Explanation",
      duration: 5.5,
      simpleText: "The strongest explanation rises to the top.",
      technicalText: "Candidates are ranked using the existing attribution framework without access to planted ground-truth labels.",
      annotationBadge: "TOP-RANKED CAUSAL DRIVER",
      annotationSub: "Loci 10 × 31 Epistatic Coupling (Attribution Score: +4.82)",
    },
  ],
};

export const COUNTERFACTUAL_RESCUE_EXPLANATION: PageExplanationConfig = {
  pageKey: "counterfactual-rescue",
  pageTitle: "Counterfactual Rescue",
  scientificQuestion: "Does changing the candidate configuration remove the novelty?",
  totalDuration: 25,
  finalThesis: "Change the configuration. Test the explanation.",
  technicalDetail: {
    title: "In-Silico Counterfactual Perturbation & Minimal Rescue",
    biologicalContext: "Prior to wet-lab CRISPR or breeding intervention, researchers need to determine which precise genetic changes will effectively rescue an extreme phenotype without unintended pleiotropic disruptions.",
    computationalRole: "Applies in-silico variant reversion, segment swapping, or interaction-edge ablation. Solves for the minimal cardinality subset S* such that y(x_S*) falls within the parental envelope [P_min, P_max].",
    formula: "S^* = \\arg\\min_{S \\subseteq \\mathcal{C}} |S| \\quad \\text{s.t.} \\quad y(x_{-S}, x_S^{\\text{ref}}) \\in [P_{\\min}, P_{\\max}]",
    keyTakeaway: "Minimal rescue pinpoints the highest-leverage molecular targets for experimental prioritization.",
  },
  scenes: [
    {
      id: "select-candidate",
      index: 0,
      title: "Select Candidate",
      duration: 5,
      simpleText: "We first choose the part we want to test.",
      technicalText: "A candidate variant, inherited segment, or modeled interaction is selected from the attribution results.",
      annotationBadge: "SELECT CANDIDATE TARGET",
      annotationSub: "IN-SILICO ONLY · Attribution Candidate Pool",
    },
    {
      id: "in-silico-intervention",
      index: 1,
      title: "In-Silico Intervention",
      duration: 5.5,
      simpleText: "We change it on the computer.",
      technicalText: "A counterfactual intervention reverts a variant, swaps a segment, or disables an interaction edge.",
      annotationBadge: "IN-SILICO INTERVENTION",
      annotationSub: "Variant Reversion / Segment Swap / Edge Ablation",
    },
    {
      id: "recompute-phenotype",
      index: 2,
      title: "Recompute Phenotype",
      duration: 5,
      simpleText: "Then we calculate the result again.",
      technicalText: "The configured phenotype model is reevaluated after the intervention.",
      annotationBadge: "PHENOTYPE RECOMPUTATION",
      annotationSub: "Evaluating Perturbed Genotype State Under Trait Model",
    },
    {
      id: "rescue-test",
      index: 3,
      title: "Rescue Test",
      duration: 5.5,
      simpleText: "If the unusual result disappears, that gives us stronger evidence.",
      technicalText: "novelty_removed becomes true when the counterfactual phenotype returns to the parental envelope.",
      annotationBadge: "RESCUE STATUS: NOVELTY REMOVED",
      annotationSub: "Parental Envelope Restored: y ∈ [P_min, P_max]",
    },
    {
      id: "minimal-rescue",
      index: 4,
      title: "Minimal Rescue",
      duration: 5.5,
      simpleText: "We also search for the smallest change that works.",
      technicalText: "The minimal rescue set is cardinality-minimal within the evaluated candidate pool.",
      annotationBadge: "MINIMAL RESCUE ANALYSIS",
      annotationSub: "Minimal Within Evaluated Candidate Subset",
    },
  ],
};

export const VALIDATION_EXPLANATION: PageExplanationConfig = {
  pageKey: "validation",
  pageTitle: "Validation Framework",
  scientificQuestion: "How do we know the framework is recovering meaningful explanations?",
  totalDuration: 32,
  finalThesis: "Trust comes from what survives testing.",
  technicalDetail: {
    title: "Empirical Synthetic Benchmark & Blind Recovery Calibration",
    biologicalContext: "Without ground-truth verification across controlled simulations, attribution methods risk confirmation bias or overfitting to background noise.",
    computationalRole: "Evaluates production inference across 200+ multi-seed synthetic worlds with planted causal mechanisms. Tests exact mechanism recovery, rescue equivalence, causal vs null delta separation, and negative controls.",
    formula: "\\text{Faithfulness Ratio} = \\frac{\\mathbb{E}[\\Delta z_{\\text{causal}}]}{\\mathbb{E}[\\Delta z_{\\text{null}}]} > 4.5, \\quad \\text{FPR}_{\\text{control}} < 0.02",
    keyTakeaway: "Empirical validation benchmarks method faithfulness on synthetic data without claiming clinical proof.",
  },
  scenes: [
    {
      id: "blind-testing",
      index: 0,
      title: "Blind Testing",
      duration: 4.5,
      simpleText: "The system does not get to see the answer.",
      technicalText: "Planted ground truth is kept evaluator-only and is not provided to the production attribution engine.",
      annotationBadge: "BLIND TESTING PROTOCOL",
      annotationSub: "Benchmark Creator (Planted) ╪ Attribution Engine (Blind) ╪ Evaluator",
    },
    {
      id: "independent-worlds",
      index: 1,
      title: "Many Independent Worlds",
      duration: 4.5,
      simpleText: "We repeat the test many times under different conditions.",
      technicalText: "Independent seeded synthetic worlds evaluate recovery across controlled difficulty regimes.",
      annotationBadge: "INDEPENDENT SYNTHETIC WORLDS",
      annotationSub: "Easy (Cyan) · Medium (Magenta) · Hard (Gold)",
    },
    {
      id: "recovery",
      index: 2,
      title: "Recovery",
      duration: 4.5,
      simpleText: "We check whether the right explanation rises to the top.",
      technicalText: "Precision, recall, top-k recovery and mean reciprocal rank quantify blind candidate recovery.",
      annotationBadge: "BLIND ATTRIBUTION RECOVERY",
      annotationSub: "Rank 1–3 Accuracy · Causal Attribution Priority",
    },
    {
      id: "exact-vs-functional",
      index: 3,
      title: "Exact vs Functional",
      duration: 4.5,
      simpleText: "An exact match and a useful rescue are not always the same thing.",
      technicalText: "The evaluator separates exact generative representation from mechanistically sufficient rescue equivalence.",
      annotationBadge: "EXACT VS RESCUE EQUIVALENCE",
      annotationSub: "Exact Generative Ground Truth vs Rescue Sufficiency",
    },
    {
      id: "causal-vs-null",
      index: 4,
      title: "Causal vs Null",
      duration: 4.5,
      simpleText: "A meaningful candidate should change the outcome more than an unrelated one.",
      technicalText: "Counterfactual faithfulness compares phenotype deltas for planted causal versus null candidates.",
      annotationBadge: "COUNTERFACTUAL FAITHFULNESS",
      annotationSub: "Causal Δ (+4.82) vs Null Δ (+0.31) Separation",
    },
    {
      id: "negative-controls",
      index: 5,
      title: "Negative Controls",
      duration: 4.5,
      simpleText: "We also test situations where the system should say 'nothing special happened.'",
      technicalText: "Negative controls check near-zero non-additivity, absence of false rescue, and correct provenance specificity.",
      annotationBadge: "NEGATIVE CONTROL INTEGRITY",
      annotationSub: "Additive, Non-Transgressive, & Unrelated Crossover Controls",
    },
    {
      id: "confidence-limitations",
      index: 6,
      title: "Confidence & Limitations",
      duration: 5.0,
      simpleText: "Good science also tells us where the method can fail.",
      technicalText: "Bootstrap intervals summarize synthetic benchmark uncertainty; they do not establish biological or clinical validity.",
      annotationBadge: "UNCERTAINTY & AUDIT",
      annotationSub: "Bootstrap Confidence Limits · No Clinical Claims",
    },
  ],
};
