"""Canonical synthetic execution adapter.

The copied scientific engine contains the detailed attribution algorithms. This
module is the narrow, typed adapter that turns those results into the public
run contract. Keeping that conversion here prevents FastAPI handlers from
knowing about legacy dataclasses or NetworkX internals.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app.domain.novelty import novelty_margin
from app.infrastructure.runtime import code_revision
from app.schemas.common import (
    BreakpointConfidence,
    CandidateKind,
    DataDisclosure,
    EvidenceStatus,
    ProvenanceMetadata,
    RunMode,
    SourceArtifactReference,
)
from app.schemas.counterfactual import CounterfactualResult as ApiCounterfactualResult
from app.schemas.genome import (
    CrossoverSnapshot,
    GameteSnapshot,
    GenomeSnapshot,
    LocusProvenanceSnapshot,
    LocusSnapshot,
    OffspringSnapshot,
    ParentGenomeSnapshot,
)
from app.schemas.genome import (
    SegmentProvenance as ApiSegmentProvenance,
)
from app.schemas.phenotype import (
    NoveltyResult,
    PhenotypeBundle,
    PhenotypeContribution,
    PhenotypeResult,
)
from app.schemas.run import CreateRunRequest, RunSnapshot
from app.schemas.trace import EvidenceGraph, EvidenceLink, EvidenceNode, TraceCandidate, TraceResponse
from app.scientific.synthetic.attribution import (
    CounterfactualResult as RawCounterfactualResult,
)
from app.scientific.synthetic.attribution import (
    NoveltyTracer,
)
from app.scientific.synthetic.phenotype import PhenotypeConfig, PhenotypeEngine, get_default_demo_phenotype_config
from app.scientific.synthetic.recombination import (
    Gamete,
    Locus,
    OffspringGenome,
    ParentGenome,
    fertilize,
    generate_loci,
    generate_synthetic_parents,
    get_rng,
    simulate_meiosis,
)

LIMITATIONS = [
    "Phenotype values are generated by an explicit synthetic model.",
    "Counterfactuals are model-relative computational evidence, not biological causality.",
    "Synthetic crossover coordinates are exact within the simulator; real-data intervals are inferred.",
]


@dataclass
class SyntheticExecution:
    request: CreateRunRequest
    loci: list[Locus]
    parent_a: ParentGenome
    parent_b: ParentGenome
    gamete_a: Gamete
    gamete_b: Gamete
    offspring: OffspringGenome
    phenotype_config: PhenotypeConfig
    phenotype_engine: PhenotypeEngine
    tracer: NoveltyTracer
    ranked_results: list[RawCounterfactualResult]
    locus_source_ids: list[str] = field(default_factory=list)
    source_artifacts: list[SourceArtifactReference] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    data_disclosure: DataDisclosure | None = None
    crossover_confidence: BreakpointConfidence = BreakpointConfidence.EXACT
    crossover_coordinates_a: list[tuple[int, int, int]] = field(default_factory=list)
    crossover_coordinates_b: list[tuple[int, int, int]] = field(default_factory=list)


def _crossover_snapshots(
    gamete: Gamete,
    confidence: BreakpointConfidence = BreakpointConfidence.EXACT,
    coordinates: list[tuple[int, int, int]] | None = None,
) -> list[CrossoverSnapshot]:
    snapshots: list[CrossoverSnapshot] = []
    current_homolog = 0
    for index, breakpoint in enumerate(gamete.crossovers):
        public_breakpoint, interval_start, interval_end = (
            coordinates[index] if coordinates and index < len(coordinates) else (breakpoint, breakpoint, breakpoint)
        )
        left = f"{gamete.parent_id}{current_homolog + 1}"
        right = f"{gamete.parent_id}{2 - current_homolog}"
        snapshots.append(
            CrossoverSnapshot(
                crossover_id=f"xo_{gamete.parent_id.lower()}_{index + 1:02d}",
                parent_id=gamete.parent_id,
                breakpoint=public_breakpoint,
                interval_start=interval_start,
                interval_end=interval_end,
                left_haplotype=left,
                right_haplotype=right,
                confidence=confidence,
                evidence_status=(EvidenceStatus.OBSERVED if confidence == BreakpointConfidence.EXACT else EvidenceStatus.INFERRED),
            )
        )
        current_homolog = 1 - current_homolog
    return snapshots


def _segment_snapshots(
    gamete: Gamete,
    confidence: BreakpointConfidence = BreakpointConfidence.EXACT,
    coordinates: list[tuple[int, int, int]] | None = None,
) -> list[ApiSegmentProvenance]:
    crossovers = _crossover_snapshots(gamete, confidence, coordinates)
    result: list[ApiSegmentProvenance] = []
    for index, segment in enumerate(gamete.segments):
        # A crossover creates the segment to its right. The first segment is
        # therefore rooted at the selected starting homolog and has no
        # creating crossover.
        crossover_id = crossovers[index - 1].crossover_id if index > 0 and index - 1 < len(crossovers) else None
        result.append(
            ApiSegmentProvenance(
                segment_id=f"seg_{gamete.parent_id.lower()}_{index + 1:02d}",
                start_locus_index=segment.start,
                end_locus_index=segment.end,
                source_parent=f"parent_{gamete.parent_id.lower()}",
                source_haplotype_id=segment.source_homolog,
                crossover_id=crossover_id,
                confidence=confidence,
                evidence_status=EvidenceStatus.INFERRED,
            )
        )
    return result


def _gamete_snapshot(
    gamete: Gamete,
    confidence: BreakpointConfidence = BreakpointConfidence.EXACT,
    coordinates: list[tuple[int, int, int]] | None = None,
) -> GameteSnapshot:
    return GameteSnapshot(
        parent_id=gamete.parent_id,
        alleles=list(gamete.alleles),
        crossovers=_crossover_snapshots(gamete, confidence, coordinates),
        segments=_segment_snapshots(gamete, confidence, coordinates),
    )


def _parent_snapshot(parent: ParentGenome, source_ids: list[str] | None = None) -> ParentGenomeSnapshot:
    loci = [
        LocusSnapshot(
            locus_id=locus.id,
            chromosome=locus.chromosome,
            position=locus.position,
            allele_values=list(locus.alleles),
            source_variant_id=(source_ids[index] if source_ids and index < len(source_ids) else None),
        )
        for index, locus in enumerate(parent.loci)
    ]
    return ParentGenomeSnapshot(
        parent_id=parent.parent_id,
        haplotypes={f"{parent.parent_id}1": list(parent.homolog_1), f"{parent.parent_id}2": list(parent.homolog_2)},
        dosage=parent.get_dosage(),
        loci=loci,
    )


def _genome_snapshot(execution: SyntheticExecution) -> GenomeSnapshot:
    offspring = execution.offspring
    return GenomeSnapshot(
        loci=[
            LocusSnapshot(
                locus_id=l.id,
                chromosome=l.chromosome,
                position=l.position,
                allele_values=list(l.alleles),
                source_variant_id=(execution.locus_source_ids[index] if index < len(execution.locus_source_ids) else None),
            )
            for index, l in enumerate(execution.loci)
        ],
        parent_a=_parent_snapshot(execution.parent_a, execution.locus_source_ids),
        parent_b=_parent_snapshot(execution.parent_b, execution.locus_source_ids),
        gamete_a=_gamete_snapshot(execution.gamete_a, execution.crossover_confidence, execution.crossover_coordinates_a),
        gamete_b=_gamete_snapshot(execution.gamete_b, execution.crossover_confidence, execution.crossover_coordinates_b),
        offspring=OffspringSnapshot(
            offspring_id=offspring.offspring_id,
            maternal_gamete=_gamete_snapshot(offspring.maternal_gamete, execution.crossover_confidence, execution.crossover_coordinates_a),
            paternal_gamete=_gamete_snapshot(offspring.paternal_gamete, execution.crossover_confidence, execution.crossover_coordinates_b),
            dosage=offspring.get_dosage(),
            locus_provenance=[LocusProvenanceSnapshot.model_validate(item.to_dict()) for item in offspring.loci_provenance],
        ),
    )


def _formula(config: PhenotypeConfig) -> str:
    terms = [f"{config.base_value}"] if config.base_value else []
    terms.extend(f"{coefficient}*{locus}" for locus, coefficient in config.additive.items())
    terms.extend(f"{coefficient}*Dom({locus})" for locus, coefficient in config.dominance.items())
    terms.extend(f"{coefficient}*Rec({locus})" for locus, coefficient in config.recessive.items())
    terms.extend(f"{pair.coefficient}*({pair.locus_a}×{pair.locus_b})" for pair in config.epistasis)
    return "P = " + " + ".join(terms) if terms else "P = 0"


def _phenotype_result(subject_id: str, breakdown, config: PhenotypeConfig) -> PhenotypeResult:
    contributions: list[PhenotypeContribution] = []
    for locus, coefficient in config.additive.items():
        value = breakdown.additive_details.get(locus, 0.0)
        contributions.append(PhenotypeContribution(term_id=f"additive_{locus}", term_type="additive", loci=[locus], value=value, active=value != 0))
    for locus, coefficient in config.dominance.items():
        value = breakdown.dominance_details.get(locus, 0.0)
        contributions.append(PhenotypeContribution(term_id=f"dominance_{locus}", term_type="dominance", loci=[locus], value=value, active=value != 0))
    for locus, coefficient in config.recessive.items():
        value = breakdown.recessive_details.get(locus, 0.0)
        contributions.append(PhenotypeContribution(term_id=f"recessive_{locus}", term_type="recessive", loci=[locus], value=value, active=value != 0))
    for pair in config.epistasis:
        value = breakdown.epistatic_details.get(pair.id, 0.0)
        contributions.append(PhenotypeContribution(term_id=pair.id, term_type="epistasis", loci=[pair.locus_a, pair.locus_b], value=value, active=value != 0))
    if breakdown.noise_component:
        contributions.append(PhenotypeContribution(term_id="noise", term_type="noise", loci=[], value=breakdown.noise_component, active=True))
    return PhenotypeResult(
        subject_id=subject_id,
        value=float(breakdown.total),
        contributions=contributions,
        model_id=config.model_id,
        model_version=config.model_version,
        formula=_formula(config),
    )


def _phenotype_bundle(execution: SyntheticExecution) -> PhenotypeBundle:
    engine = execution.phenotype_engine
    parent_a = _phenotype_result("parent_a", engine.evaluate_diploid(execution.parent_a.homolog_1, execution.parent_a.homolog_2), execution.phenotype_config)
    parent_b = _phenotype_result("parent_b", engine.evaluate_diploid(execution.parent_b.homolog_1, execution.parent_b.homolog_2), execution.phenotype_config)
    offspring = _phenotype_result("offspring", engine.evaluate_diploid(execution.gamete_a.alleles, execution.gamete_b.alleles), execution.phenotype_config)
    is_novel, margin, direction = novelty_margin(parent_a.value, parent_b.value, offspring.value)
    return PhenotypeBundle(
        parent_a=parent_a,
        parent_b=parent_b,
        offspring=offspring,
        novelty=NoveltyResult(
            outside_parental_range=is_novel,
            lower=min(parent_a.value, parent_b.value),
            upper=max(parent_a.value, parent_b.value),
            offspring_value=offspring.value,
            margin=margin,
            direction=direction,
        ),
    )


def _raw_target(result: RawCounterfactualResult) -> dict[str, object]:
    target = result.semantics.get("target", {})
    return target if isinstance(target, dict) else {}


def _source_haplotypes(result: RawCounterfactualResult) -> list[str]:
    return sorted(set(re.findall(r"\b[AB][12]\b", result.provenance_summary)))


def _crossover_ids(execution: SyntheticExecution, target: dict[str, object]) -> list[str]:
    start = int(target.get("start", target.get("locus_a_pos", 0)) or 0)
    end = int(target.get("end", target.get("locus_b_pos", start)) or start)
    identifiers: list[str] = []
    for parent, events in (("a", execution.tracer.inferred_events_a), ("b", execution.tracer.inferred_events_b)):
        for index, event in enumerate(events):
            if start <= event.inferred_breakpoint <= end:
                identifiers.append(f"xo_{parent}_{index + 1:02d}")
    return identifiers


def _trace_candidate(execution: SyntheticExecution, result: RawCounterfactualResult, rank: int) -> TraceCandidate:
    target = _raw_target(result)
    kind = CandidateKind(result.candidate_type.lower())
    source_by_internal_id = dict(zip((locus.id for locus in execution.loci), execution.locus_source_ids))
    loci = [
        source_by_internal_id.get(str(target[key]), str(target[key]))
        for key in ("locus_id", "locus_a", "locus_b")
        if target.get(key)
    ]
    parent = target.get("parent")
    parents = [f"parent_{str(parent).lower()}"] if parent in {"A", "B"} else ["parent_a", "parent_b"]
    return TraceCandidate(
        candidate_id=result.candidate_id,
        kind=kind,
        rank=rank,
        label=result.candidate_name,
        loci=loci,
        source_parents=parents,
        source_haplotypes=_source_haplotypes(result),
        crossover_ids=_crossover_ids(execution, target),
        provenance_score=float(result.provenance_score),
        phenotype_delta=float(result.delta),
        attribution_score=float(result.attribution_score),
        novelty_resolved=bool(result.novelty_removed),
        reason=result.provenance_summary,
        evidence_status=EvidenceStatus.INFERRED,
    )


def _evidence_graph(execution: SyntheticExecution, results: list[RawCounterfactualResult]) -> EvidenceGraph:
    raw = execution.tracer.build_evidence_graph(results)
    nodes: list[EvidenceNode] = []
    for node in raw.get("nodes", []):
        node_type = str(node.get("type", "evidence"))
        status = EvidenceStatus.OBSERVED if node_type in {"parent", "homolog"} else EvidenceStatus.INFERRED
        attributes = {key: value for key, value in node.items() if key not in {"id", "label", "type"}}
        nodes.append(EvidenceNode(node_id=str(node["id"]), node_type=node_type, label=str(node.get("label", node["id"])), evidence_status=status, attributes=attributes))
    links: list[EvidenceLink] = []
    known = {node.node_id for node in nodes}
    for link in raw.get("links", []):
        source, target = str(link["source"]), str(link["target"])
        if source not in known or target not in known:
            continue
        links.append(EvidenceLink(source=source, target=target, relation=str(link.get("relationship", "related_to")), evidence_status=EvidenceStatus.INFERRED))
    return EvidenceGraph(nodes=sorted(nodes, key=lambda item: item.node_id), links=sorted(links, key=lambda item: (item.source, item.target, item.relation)))


def _counterfactual_result(execution: SyntheticExecution, run_id: str, raw: RawCounterfactualResult) -> ApiCounterfactualResult:
    target = _raw_target(raw)
    original = _phenotype_result(
        "offspring",
        execution.phenotype_engine.evaluate_diploid(execution.gamete_a.alleles, execution.gamete_b.alleles),
        execution.phenotype_config,
    )
    altered = raw.semantics.get("altered_state", {})
    h1 = altered.get("h1", execution.gamete_a.alleles) if isinstance(altered, dict) else execution.gamete_a.alleles
    h2 = altered.get("h2", execution.gamete_b.alleles) if isinstance(altered, dict) else execution.gamete_b.alleles
    disabled_pairs: set[tuple[int, int]] = set()
    if isinstance(altered, dict):
        for pair in altered.get("disabled_pairs") or []:
            if isinstance(pair, (list, tuple)) and len(pair) == 2:
                try:
                    disabled_pairs.add((int(pair[0]), int(pair[1])))
                except (TypeError, ValueError):
                    continue
    counterfactual = _phenotype_result("offspring_counterfactual", execution.phenotype_engine.evaluate_diploid(list(h1), list(h2)), execution.phenotype_config)
    if disabled_pairs:
        counterfactual = _phenotype_result(
            "offspring_counterfactual",
            execution.phenotype_engine.evaluate_diploid(
                list(h1), list(h2), broken_pairs=disabled_pairs
            ),
            execution.phenotype_config,
        )
    changed_loci = [str(value) for key in ("locus_id", "locus_a", "locus_b") if (value := target.get(key))]
    intervention = {
        "break_interaction": "break_interaction",
        "swap_segment": "swap_segment",
        "remove_segment": "swap_segment",
        "revert_variant": "revert_variant",
        "replace_with_parent_a_genotype": "revert_variant",
        "replace_with_parent_b_genotype": "revert_variant",
    }.get(raw.intervention, "revert_variant")
    return ApiCounterfactualResult(
        intervention_id=f"int_{run_id}_{raw.candidate_id}_{intervention}",
        run_id=run_id,
        candidate_id=raw.candidate_id,
        intervention=intervention,
        original=original,
        counterfactual=counterfactual,
        delta=float(raw.delta),
        novelty_resolved=bool(raw.novelty_removed),
        changed_loci=changed_loci,
        explanation="Recomputed under the configured synthetic phenotype model; this is computational evidence, not biological proof.",
        baseline_phenotype=(raw.baseline_phenotype if raw.interaction_contrast is not None else None),
        phenotype_after_a=raw.phenotype_after_a,
        phenotype_after_b=raw.phenotype_after_b,
        phenotype_after_ab=raw.phenotype_after_ab,
        delta_a=raw.delta_a,
        delta_b=raw.delta_b,
        delta_ab=raw.delta_ab,
        interaction_contrast=raw.interaction_contrast,
        epistatic_excess=raw.epistatic_excess,
        interaction_edge_delta=raw.interaction_edge_delta,
        novelty_removed_a=raw.novelty_removed_a,
        novelty_removed_b=raw.novelty_removed_b,
        novelty_removed_ab=raw.novelty_removed_ab,
        parental_envelope=raw.parental_envelope,
        synergy_direction=raw.synergy_direction,
        provenance=raw.provenance,
    )


def _trace(execution: SyntheticExecution, run_id: str) -> TraceResponse:
    results = execution.ranked_results
    return TraceResponse(
        run_id=run_id,
        novelty_available=execution.tracer.baseline_novelty.is_transgressive,
        ranking_definition="Counterfactual phenotype delta combined with provenance, novelty resolution, recombination support and a complexity penalty.",
        candidates=[_trace_candidate(execution, result, index) for index, result in enumerate(results, start=1)],
        graph=_evidence_graph(execution, results),
        limitations=LIMITATIONS,
    )


def build_snapshot(execution: SyntheticExecution, run_id: str, counterfactuals: list[ApiCounterfactualResult] | None = None) -> RunSnapshot:
    now = datetime.now(timezone.utc)
    return RunSnapshot(
        run_id=run_id,
        status="completed",
        mode=execution.request.mode,
        seed=execution.request.seed,
        stage="complete",
        dataset_id=execution.request.dataset_id,
        genome=_genome_snapshot(execution),
        phenotype=_phenotype_bundle(execution),
        candidates=_trace(execution, run_id).candidates,
        evidence_graph=_trace(execution, run_id).graph,
        counterfactuals=counterfactuals or [],
        reproducibility=ProvenanceMetadata(
            seed=execution.request.seed,
            dataset_id=execution.request.dataset_id,
            model_id=execution.request.phenotype_model_id,
            model_version=execution.phenotype_config.model_version,
            code_revision=code_revision(),
            generated_at=now,
            disclosure=(
                "All genotypes, inheritance events and phenotype values are synthetic."
                if execution.request.mode == RunMode.SYNTHETIC
                else "Genotypes and inheritance relationships are real public data. Phenotype values and interaction rules are synthetic for method validation."
            ),
        ),
        limitations=LIMITATIONS,
        disclosure=execution.data_disclosure or DataDisclosure(
            dataset_kind="synthetic",
            genotype_source="Generated synthetic haplotypes",
            phenotype_source=execution.phenotype_config.disclosure,
            causal_interpretation="Counterfactual computational evidence relative to the configured model; not biological proof.",
        ),
        source_artifacts=execution.source_artifacts,
        warnings=execution.warnings,
    )


def execute_synthetic(request: CreateRunRequest) -> SyntheticExecution:
    count = request.options.locus_count
    loci = generate_loci(count)
    fixture = request.dataset_id == "fixture_epistasis_ab_cd_v1"
    parent_a, parent_b = generate_synthetic_parents(loci, seed=request.seed, stochastic=not fixture)
    if fixture and count >= 35:
        crossover_a, crossover_b = [20], [15]
        start_a, start_b = 0, 0
    else:
        rng = get_rng(request.seed)
        crossover_a = [int(rng.integers(5, count - 5))]
        crossover_b = [int(rng.integers(5, count - 5))]
        start_a, start_b = request.seed % 2, (request.seed + 1) % 2
    gamete_a = simulate_meiosis(parent_a.homolog_1, parent_a.homolog_2, "A", crossover_positions=crossover_a, start_homolog=start_a, rng=get_rng(request.seed + 101))
    gamete_b = simulate_meiosis(parent_b.homolog_1, parent_b.homolog_2, "B", crossover_positions=crossover_b, start_homolog=start_b, rng=get_rng(request.seed + 202))
    offspring = fertilize(gamete_a, gamete_b, loci)
    config = get_default_demo_phenotype_config()
    config.model_id = request.phenotype_model_id
    config.epistasis = config.epistasis[: request.options.candidate_interactions]
    config.noise_sigma = 0.5 if request.options.include_noise else 0.0
    engine = PhenotypeEngine(config)
    tracer = NoveltyTracer(parent_a, parent_b, offspring, engine, candidate_limit=request.options.max_candidates)
    ranked = tracer.rank_candidates()
    return SyntheticExecution(request, loci, parent_a, parent_b, gamete_a, gamete_b, offspring, config, engine, tracer, ranked)


def trace_response(execution: SyntheticExecution, run_id: str) -> TraceResponse:
    return _trace(execution, run_id)


def counterfactual_response(execution: SyntheticExecution, run_id: str, raw: RawCounterfactualResult) -> ApiCounterfactualResult:
    return _counterfactual_result(execution, run_id, raw)
